import type { DoorState } from "../simulation/types";

export const createDoors = (): DoorState[] => [
  {
    id: "door-left-studio-upper",
    assetKey: "scifi-door",
    hinge: { x: 359, y: 302 },
    length: 56,
    thickness: 12,
    closedAngle: Math.PI / 2,
    openAngle: Math.PI * 0.1,
    minAngle: -0.2,
    maxAngle: Math.PI - 0.2,
    angle: Math.PI / 2,
    targetAngle: Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-left-studio-lower",
    assetKey: "scifi-door",
    hinge: { x: 359, y: 414 },
    length: 56,
    thickness: 12,
    closedAngle: -Math.PI / 2,
    openAngle: -Math.PI * 0.1,
    minAngle: -Math.PI + 0.2,
    maxAngle: 0.2,
    angle: -Math.PI / 2,
    targetAngle: -Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-right-studio-upper",
    assetKey: "scifi-door",
    hinge: { x: 823, y: 298 },
    length: 56,
    thickness: 12,
    closedAngle: Math.PI / 2,
    openAngle: Math.PI * 0.9,
    minAngle: 0.2,
    maxAngle: Math.PI + 0.2,
    angle: Math.PI / 2,
    targetAngle: Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-right-studio-lower",
    assetKey: "scifi-door",
    hinge: { x: 823, y: 410 },
    length: 56,
    thickness: 12,
    closedAngle: -Math.PI / 2,
    openAngle: -Math.PI * 0.9,
    minAngle: -Math.PI - 0.2,
    maxAngle: -0.2,
    angle: -Math.PI / 2,
    targetAngle: -Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-center-news-left",
    assetKey: "scifi-door-small",
    hinge: { x: 648, y: 301 },
    length: 34,
    thickness: 12,
    closedAngle: 0,
    openAngle: -Math.PI / 2,
    minAngle: -Math.PI / 2,
    maxAngle: Math.PI / 2,
    angle: 0,
    targetAngle: 0,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-center-news-right",
    assetKey: "scifi-door-small",
    hinge: { x: 716, y: 301 },
    length: 34,
    thickness: 12,
    closedAngle: Math.PI,
    openAngle: Math.PI / 2,
    minAngle: Math.PI / 2,
    maxAngle: Math.PI * 1.5,
    angle: Math.PI,
    targetAngle: Math.PI,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
];
