import type { DoorState } from "../simulation/types";

const LEAF_LENGTH = 56;
const LEAF_THICKNESS = 7;

export const createDoors = (): DoorState[] => [
  {
    id: "door-left-studio-upper",
    assetKey: "scifi-door",
    hinge: { x: 359, y: 302 },
    length: LEAF_LENGTH,
    thickness: LEAF_THICKNESS,
    closedAngle: Math.PI / 2,
    openAngle: 0,
    minAngle: 0,
    maxAngle: Math.PI,
    angle: Math.PI / 2,
    targetAngle: Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-left-studio-lower",
    assetKey: "scifi-door",
    hinge: { x: 359, y: 302 + LEAF_LENGTH * 2 },
    length: LEAF_LENGTH,
    thickness: LEAF_THICKNESS,
    closedAngle: -Math.PI / 2,
    openAngle: 0,
    minAngle: -Math.PI,
    maxAngle: 0,
    angle: -Math.PI / 2,
    targetAngle: -Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-right-studio-upper",
    assetKey: "scifi-door",
    hinge: { x: 823, y: 298 },
    length: LEAF_LENGTH,
    thickness: LEAF_THICKNESS,
    closedAngle: Math.PI / 2,
    openAngle: Math.PI,
    minAngle: 0,
    maxAngle: Math.PI,
    angle: Math.PI / 2,
    targetAngle: Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-right-studio-lower",
    assetKey: "scifi-door",
    hinge: { x: 823, y: 298 + LEAF_LENGTH * 2 },
    length: LEAF_LENGTH,
    thickness: LEAF_THICKNESS,
    closedAngle: -Math.PI / 2,
    openAngle: -Math.PI,
    minAngle: -Math.PI,
    maxAngle: 0,
    angle: -Math.PI / 2,
    targetAngle: -Math.PI / 2,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
  {
    id: "door-center-news",
    assetKey: "scifi-door",
    hinge: { x: 648, y: 301 },
    length: LEAF_LENGTH,
    thickness: LEAF_THICKNESS,
    closedAngle: 0,
    openAngle: -Math.PI / 2,
    minAngle: -Math.PI / 2,
    maxAngle: Math.PI / 2,
    angle: 0,
    targetAngle: 0,
    angularVelocity: 0,
    state: "closed",
    blocksBullets: true,
  },
];
